<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="CodeIgniter Application Test Suite" tests="24" assertions="54" errors="2" failures="1" skipped="2" time="0.342141">
    <testsuite name="Cidade_model_test" file="C:\Users\sandr\xampp\htdocs\rpv\application\tests\models\Cidade_model_test.php" tests="4" assertions="4" errors="0" failures="0" skipped="0" time="0.084331">
      <testcase name="testGetCidadeError" class="Cidade_model_test" classname="Cidade_model_test" file="C:\Users\sandr\xampp\htdocs\rpv\application\tests\models\Cidade_model_test.php" line="20" assertions="1" time="0.019167">
        <system-out>&#13;
&#13;
</system-out>
      </testcase>
      <testcase name="testGetCidadeSucess" class="Cidade_model_test" classname="Cidade_model_test" file="C:\Users\sandr\xampp\htdocs\rpv\application\tests\models\Cidade_model_test.php" line="26" assertions="1" time="0.019340">
        <system-out>&#13;
&#13;
&#13;
A PHP Error was encountered&#13;
&#13;
Severity:    Notice
Message:     Undefined index: cidade_nome
Filename:    C:\Users\sandr\xampp\htdocs\rpv\application\tests\models\Cidade_model_test.php
Line Number: 29&#13;
&#13;
Backtrace:&#13;
	File: C:\Users\sandr\xampp\htdocs\rpv\application\tests\models\Cidade_model_test.php
	Line: 29
	Function: _error_handler

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/Framework/TestCase.php
	Line: 1153
	Function: testGetCidadeSucess

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/Framework/TestCase.php
	Line: 842
	Function: runTest

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/Framework/TestResult.php
	Line: 687
	Function: runBare

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/Framework/TestCase.php
	Line: 796
	Function: run

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/Framework/TestSuite.php
	Line: 746
	Function: run

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/Framework/TestSuite.php
	Line: 746
	Function: run

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/TextUI/TestRunner.php
	Line: 641
	Function: run

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/TextUI/Command.php
	Line: 206
	Function: doRun

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/TextUI/Command.php
	Line: 162
	Function: run

	File: C:\Users\sandr\xampp\php\phpunit
	Line: 614
	Function: main

&#13;
</system-out>
      </testcase>
      <testcase name="testGetCidadeEspecifica" class="Cidade_model_test" classname="Cidade_model_test" file="C:\Users\sandr\xampp\htdocs\rpv\application\tests\models\Cidade_model_test.php" line="32" assertions="1" time="0.017570">
        <system-out>&#13;
&#13;
</system-out>
      </testcase>
      <testcase name="testGetTodasCidades" class="Cidade_model_test" classname="Cidade_model_test" file="C:\Users\sandr\xampp\htdocs\rpv\application\tests\models\Cidade_model_test.php" line="38" assertions="1" time="0.028254">
        <system-out>&#13;
&#13;
</system-out>
      </testcase>
    </testsuite>
    <testsuite name="Estado_model_test" file="C:\Users\sandr\xampp\htdocs\rpv\application\tests\models\Estado_model_test.php" tests="6" assertions="6" errors="0" failures="0" skipped="0" time="0.083485">
      <testcase name="testGetEstadoError" class="Estado_model_test" classname="Estado_model_test" file="C:\Users\sandr\xampp\htdocs\rpv\application\tests\models\Estado_model_test.php" line="19" assertions="1" time="0.011752">
        <system-out>&#13;
&#13;
</system-out>
      </testcase>
      <testcase name="testGetEstadoSucess" class="Estado_model_test" classname="Estado_model_test" file="C:\Users\sandr\xampp\htdocs\rpv\application\tests\models\Estado_model_test.php" line="25" assertions="1" time="0.017761">
        <system-out>&#13;
&#13;
&#13;
A PHP Error was encountered&#13;
&#13;
Severity:    Notice
Message:     Undefined index: estado_nome
Filename:    C:\Users\sandr\xampp\htdocs\rpv\application\tests\models\Estado_model_test.php
Line Number: 28&#13;
&#13;
Backtrace:&#13;
	File: C:\Users\sandr\xampp\htdocs\rpv\application\tests\models\Estado_model_test.php
	Line: 28
	Function: _error_handler

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/Framework/TestCase.php
	Line: 1153
	Function: testGetEstadoSucess

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/Framework/TestCase.php
	Line: 842
	Function: runTest

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/Framework/TestResult.php
	Line: 687
	Function: runBare

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/Framework/TestCase.php
	Line: 796
	Function: run

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/Framework/TestSuite.php
	Line: 746
	Function: run

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/Framework/TestSuite.php
	Line: 746
	Function: run

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/TextUI/TestRunner.php
	Line: 641
	Function: run

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/TextUI/Command.php
	Line: 206
	Function: doRun

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/TextUI/Command.php
	Line: 162
	Function: run

	File: C:\Users\sandr\xampp\php\phpunit
	Line: 614
	Function: main

&#13;
</system-out>
      </testcase>
      <testcase name="testGetUFSucess" class="Estado_model_test" classname="Estado_model_test" file="C:\Users\sandr\xampp\htdocs\rpv\application\tests\models\Estado_model_test.php" line="31" assertions="1" time="0.024181">
        <system-out>&#13;
&#13;
&#13;
A PHP Error was encountered&#13;
&#13;
Severity:    Notice
Message:     Undefined index: estado_uf
Filename:    C:\Users\sandr\xampp\htdocs\rpv\application\tests\models\Estado_model_test.php
Line Number: 34&#13;
&#13;
Backtrace:&#13;
	File: C:\Users\sandr\xampp\htdocs\rpv\application\tests\models\Estado_model_test.php
	Line: 34
	Function: _error_handler

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/Framework/TestCase.php
	Line: 1153
	Function: testGetUFSucess

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/Framework/TestCase.php
	Line: 842
	Function: runTest

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/Framework/TestResult.php
	Line: 687
	Function: runBare

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/Framework/TestCase.php
	Line: 796
	Function: run

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/Framework/TestSuite.php
	Line: 746
	Function: run

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/Framework/TestSuite.php
	Line: 746
	Function: run

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/TextUI/TestRunner.php
	Line: 641
	Function: run

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/TextUI/Command.php
	Line: 206
	Function: doRun

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/TextUI/Command.php
	Line: 162
	Function: run

	File: C:\Users\sandr\xampp\php\phpunit
	Line: 614
	Function: main

&#13;
</system-out>
      </testcase>
      <testcase name="testGetEstadoEspecifico" class="Estado_model_test" classname="Estado_model_test" file="C:\Users\sandr\xampp\htdocs\rpv\application\tests\models\Estado_model_test.php" line="37" assertions="1" time="0.009034">
        <system-out>&#13;
&#13;
</system-out>
      </testcase>
      <testcase name="testGetUFEspecifico" class="Estado_model_test" classname="Estado_model_test" file="C:\Users\sandr\xampp\htdocs\rpv\application\tests\models\Estado_model_test.php" line="42" assertions="1" time="0.010995">
        <system-out>&#13;
&#13;
</system-out>
      </testcase>
      <testcase name="testGetTodosEstados" class="Estado_model_test" classname="Estado_model_test" file="C:\Users\sandr\xampp\htdocs\rpv\application\tests\models\Estado_model_test.php" line="49" assertions="1" time="0.009761">
        <system-out>&#13;
&#13;
</system-out>
      </testcase>
    </testsuite>
    <testsuite name="Onibus_model_test" file="C:\Users\sandr\xampp\htdocs\rpv\application\tests\models\Onibus_model_test.php" tests="5" assertions="3" errors="2" failures="1" skipped="0" time="0.070754">
      <testcase name="testGetPlacaOnibusTest" class="Onibus_model_test" classname="Onibus_model_test" file="C:\Users\sandr\xampp\htdocs\rpv\application\tests\models\Onibus_model_test.php" line="22" assertions="0" time="0.020885">
        <error type="PHPUnit\Framework\RiskyTestError">Risky Test
</error>
        <system-out>&#13;
&#13;
&#13;
A PHP Error was encountered&#13;
&#13;
Severity:    Notice
Message:     Undefined index: result
Filename:    C:\Users\sandr\xampp\htdocs\rpv\application\tests\models\Onibus_model_test.php
Line Number: 26&#13;
&#13;
Backtrace:&#13;
	File: C:\Users\sandr\xampp\htdocs\rpv\application\tests\models\Onibus_model_test.php
	Line: 26
	Function: _error_handler

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/Framework/TestCase.php
	Line: 1153
	Function: testGetPlacaOnibusTest

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/Framework/TestCase.php
	Line: 842
	Function: runTest

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/Framework/TestResult.php
	Line: 687
	Function: runBare

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/Framework/TestCase.php
	Line: 796
	Function: run

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/Framework/TestSuite.php
	Line: 746
	Function: run

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/Framework/TestSuite.php
	Line: 746
	Function: run

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/TextUI/TestRunner.php
	Line: 641
	Function: run

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/TextUI/Command.php
	Line: 206
	Function: doRun

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/TextUI/Command.php
	Line: 162
	Function: run

	File: C:\Users\sandr\xampp\php\phpunit
	Line: 614
	Function: main

&#13;
&#13;
A PHP Error was encountered&#13;
&#13;
Severity:    Warning
Message:     sizeof(): Parameter must be an array or an object that implements Countable
Filename:    C:\Users\sandr\xampp\htdocs\rpv\application\tests\models\Onibus_model_test.php
Line Number: 26&#13;
&#13;
Backtrace:&#13;
	File: C:\Users\sandr\xampp\htdocs\rpv\application\tests\models\Onibus_model_test.php
	Line: 26
	Function: sizeof

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/Framework/TestCase.php
	Line: 1153
	Function: testGetPlacaOnibusTest

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/Framework/TestCase.php
	Line: 842
	Function: runTest

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/Framework/TestResult.php
	Line: 687
	Function: runBare

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/Framework/TestCase.php
	Line: 796
	Function: run

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/Framework/TestSuite.php
	Line: 746
	Function: run

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/Framework/TestSuite.php
	Line: 746
	Function: run

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/TextUI/TestRunner.php
	Line: 641
	Function: run

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/TextUI/Command.php
	Line: 206
	Function: doRun

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/TextUI/Command.php
	Line: 162
	Function: run

	File: C:\Users\sandr\xampp\php\phpunit
	Line: 614
	Function: main

&#13;
</system-out>
      </testcase>
      <testcase name="testGetChassiOnibusTest" class="Onibus_model_test" classname="Onibus_model_test" file="C:\Users\sandr\xampp\htdocs\rpv\application\tests\models\Onibus_model_test.php" line="34" assertions="0" time="0.011628">
        <error type="PHPUnit\Framework\RiskyTestError">Risky Test
</error>
        <system-out>&#13;
&#13;
&#13;
A PHP Error was encountered&#13;
&#13;
Severity:    Notice
Message:     Undefined index: result
Filename:    C:\Users\sandr\xampp\htdocs\rpv\application\tests\models\Onibus_model_test.php
Line Number: 39&#13;
&#13;
Backtrace:&#13;
	File: C:\Users\sandr\xampp\htdocs\rpv\application\tests\models\Onibus_model_test.php
	Line: 39
	Function: _error_handler

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/Framework/TestCase.php
	Line: 1153
	Function: testGetChassiOnibusTest

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/Framework/TestCase.php
	Line: 842
	Function: runTest

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/Framework/TestResult.php
	Line: 687
	Function: runBare

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/Framework/TestCase.php
	Line: 796
	Function: run

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/Framework/TestSuite.php
	Line: 746
	Function: run

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/Framework/TestSuite.php
	Line: 746
	Function: run

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/TextUI/TestRunner.php
	Line: 641
	Function: run

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/TextUI/Command.php
	Line: 206
	Function: doRun

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/TextUI/Command.php
	Line: 162
	Function: run

	File: C:\Users\sandr\xampp\php\phpunit
	Line: 614
	Function: main

&#13;
&#13;
A PHP Error was encountered&#13;
&#13;
Severity:    Warning
Message:     sizeof(): Parameter must be an array or an object that implements Countable
Filename:    C:\Users\sandr\xampp\htdocs\rpv\application\tests\models\Onibus_model_test.php
Line Number: 39&#13;
&#13;
Backtrace:&#13;
	File: C:\Users\sandr\xampp\htdocs\rpv\application\tests\models\Onibus_model_test.php
	Line: 39
	Function: sizeof

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/Framework/TestCase.php
	Line: 1153
	Function: testGetChassiOnibusTest

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/Framework/TestCase.php
	Line: 842
	Function: runTest

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/Framework/TestResult.php
	Line: 687
	Function: runBare

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/Framework/TestCase.php
	Line: 796
	Function: run

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/Framework/TestSuite.php
	Line: 746
	Function: run

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/Framework/TestSuite.php
	Line: 746
	Function: run

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/TextUI/TestRunner.php
	Line: 641
	Function: run

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/TextUI/Command.php
	Line: 206
	Function: doRun

	File: phar://C:/Users/sandr/xampp/php/phpunit/phpunit/TextUI/Command.php
	Line: 162
	Function: run

	File: C:\Users\sandr\xampp\php\phpunit
	Line: 614
	Function: main

&#13;
</system-out>
      </testcase>
      <testcase name="testInsertionOnibusSucess" class="Onibus_model_test" classname="Onibus_model_test" file="C:\Users\sandr\xampp\htdocs\rpv\application\tests\models\Onibus_model_test.php" line="48" assertions="1" time="0.012562">
        <failure type="PHPUnit\Framework\ExpectationFailedException">Onibus_model_test::testInsertionOnibusSucess
Failed asserting that false is true.

C:\Users\sandr\xampp\htdocs\rpv\application\tests\models\Onibus_model_test.php:51
</failure>
        <system-out>&#13;
&#13;
</system-out>
      </testcase>
      <testcase name="testInsertionOnibusError" class="Onibus_model_test" classname="Onibus_model_test" file="C:\Users\sandr\xampp\htdocs\rpv\application\tests\models\Onibus_model_test.php" line="55" assertions="1" time="0.016305">
        <system-out>&#13;
&#13;
</system-out>
      </testcase>
      <testcase name="testUpdateOnibusError" class="Onibus_model_test" classname="Onibus_model_test" file="C:\Users\sandr\xampp\htdocs\rpv\application\tests\models\Onibus_model_test.php" line="62" assertions="1" time="0.009374">
        <system-out>&#13;
&#13;
</system-out>
      </testcase>
    </testsuite>
    <testsuite name="Rodoviaria_model_test" file="C:\Users\sandr\xampp\htdocs\rpv\application\tests\models\Rodoviaria_model_test.php" tests="9" assertions="41" errors="0" failures="0" skipped="2" time="0.103571">
      <testcase name="testGetRodoviariasCidadeTest" class="Rodoviaria_model_test" classname="Rodoviaria_model_test" file="C:\Users\sandr\xampp\htdocs\rpv\application\tests\models\Rodoviaria_model_test.php" line="22" assertions="35" time="0.011624">
        <system-out>&#13;
&#13;
</system-out>
      </testcase>
      <testcase name="testGetRodoviariaeEspecifica" class="Rodoviaria_model_test" classname="Rodoviaria_model_test" file="C:\Users\sandr\xampp\htdocs\rpv\application\tests\models\Rodoviaria_model_test.php" line="34" assertions="1" time="0.009707">
        <system-out>&#13;
&#13;
</system-out>
      </testcase>
      <testcase name="testInsertionRodoviariaCidadeCorreta" class="Rodoviaria_model_test" classname="Rodoviaria_model_test" file="C:\Users\sandr\xampp\htdocs\rpv\application\tests\models\Rodoviaria_model_test.php" line="43" assertions="1" time="0.014906">
        <system-out>&#13;
&#13;
</system-out>
      </testcase>
      <testcase name="testInsertionRodoviariaCidadeIncorreta" class="Rodoviaria_model_test" classname="Rodoviaria_model_test" file="C:\Users\sandr\xampp\htdocs\rpv\application\tests\models\Rodoviaria_model_test.php" line="52" assertions="1" time="0.013066">
        <system-out>&#13;
&#13;
</system-out>
      </testcase>
      <testcase name="testOverflowInsertionRodoviaria" class="Rodoviaria_model_test" classname="Rodoviaria_model_test" file="C:\Users\sandr\xampp\htdocs\rpv\application\tests\models\Rodoviaria_model_test.php" line="64" assertions="0" time="0.011325">
        <skipped/>
        <system-out>&#13;
&#13;
</system-out>
      </testcase>
      <testcase name="testUnexpectedTypeInsertionRodoviaria" class="Rodoviaria_model_test" classname="Rodoviaria_model_test" file="C:\Users\sandr\xampp\htdocs\rpv\application\tests\models\Rodoviaria_model_test.php" line="81" assertions="0" time="0.010777">
        <skipped/>
        <system-out>&#13;
&#13;
</system-out>
      </testcase>
      <testcase name="testGetQuantRodoviariaPorCidade" class="Rodoviaria_model_test" classname="Rodoviaria_model_test" file="C:\Users\sandr\xampp\htdocs\rpv\application\tests\models\Rodoviaria_model_test.php" line="91" assertions="1" time="0.008806">
        <system-out>&#13;
&#13;
</system-out>
      </testcase>
      <testcase name="testUpdateRodoviariaSuccess" class="Rodoviaria_model_test" classname="Rodoviaria_model_test" file="C:\Users\sandr\xampp\htdocs\rpv\application\tests\models\Rodoviaria_model_test.php" line="99" assertions="1" time="0.011561">
        <system-out>&#13;
&#13;
</system-out>
      </testcase>
      <testcase name="testUpdateRodoviariaError" class="Rodoviaria_model_test" classname="Rodoviaria_model_test" file="C:\Users\sandr\xampp\htdocs\rpv\application\tests\models\Rodoviaria_model_test.php" line="105" assertions="1" time="0.011799">
        <system-out>&#13;
&#13;
</system-out>
      </testcase>
    </testsuite>
  </testsuite>
</testsuites>
